### ISSUE TITLE
Avoid code duplication

### ISSUE THREAD

**Issue by zcoding** [darionco/rollup-plugin-web-worker-loader#26]
_there are better solutions for this purpose_

Do you mind tell me some solutions?

**Comment by darionco** [comment]
The idea for that task was to be able to pack the worker code and avoid code duplication of imported modules, so if your worker used `Math.gl` and your main thread also used `Math.gl` then you would only get one copy of the library.

Implementing this feature is not an easy task and would have to modify how the libraries are packed in the build process, making this plugin very prone to errors and incompatibilities with other plugins.

The solution that I found is code splitting, unfortunately [regular `import` statements are not implemented in browsers other than chrome and edge](https://caniuse.com/#feat=mdn-javascript_statements_import_worker_support) but you can use [`importScripts`](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts) which is a bit more complicated but gets the job done.

This plugin does not need to support the use of code splitting + `importScripts` because [rollup-plugin-off-main-thread](https://github.com/surma/rollup-plugin-off-main-thread) already implements this functionality and is stable. Once all major browsers implement native `import` statements in workers, no plugin will be necessary to achieve that task.

I might revisit inlining workers + avoid code duplication in the future, but I don't believe it is a priority as there are better solutions to this problem.

**Comment by darionco** [comment]
Closing for now, if you feel like this needs further explanation, feel free to continue the conversation here or open a new issue.
