### ISSUE TITLE
missing "use strict" option

### ISSUE THREAD

**Issue by krzysztofpniak** [darionco/rollup-plugin-web-worker-loader#31]
How can I add `"use strict"` at the begging of the inlined web worker script?

**Comment by darionco** [comment]
That's not possible right now, most modern platforms do not need `"use strict"` since it is enabled by default, but definitely something that can be useful for some scenarios.

I think adding an `explicitStrict` boolean option would solve this issue, I'll add it next time I work on this plugin in a couple days.


Thakns

**Comment by krzysztofpniak** [comment]
Cool, I'm looking forward to it.
Anyways, I have newest chrome and it doesn't seem to have it enabled by default, at least in web worker context.

**Comment by darionco** [comment]
Because rollup uses strict mode by default, I decided to let rollup insert `'use strict';` at its own discretion, which is always.

Released in 1.4.0

**Comment by krzysztofpniak** [comment]
Thanks for a quick action. Now it works like a charm!
