### ISSUE TITLE
Incorrect utf8/unicode handling when converting base64-encoded string to source code

### ISSUE THREAD

**Issue by feichao93** [darionco/rollup-plugin-web-worker-loader#5]
## Why this happens

We are calling `atob` to convert base64-encoded string to source code, however `atob` does not handle unicode correctly (see ["The_Unicode_Problem" on MDN ](https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#The_Unicode_Problem))

https://github.com/darionco/rollup-plugin-web-worker-loader/blob/111c2e208ddcfb56ecb31e043fa7013e1f721541/src/WorkerLoaderHelper.js#L43-L46

## Expected behavior and actual behavior

I use rollup with this rollup plugin to bundle my code, and I have some Chinese comments in my worker source code.  Chinese characters will be garbled in the bundle 😥 .

![image](https://user-images.githubusercontent.com/5550931/68066764-2d55a080-fd78-11e9-8515-3e2e5a02d676.png)

## How to fix it

The simplest solution is that we call `encodeURIComponent(...)` before we encode the source into base64 format in `buildWorkerCode`, so we can ensure there are only ascii characters in the base64-encode input. And in `createBase64WorkerFactory` we call `decodeURIComponent` after base64 decode.

**Comment by darionco** [comment]
I see, I did a little bit of research and I believe the best solution is to convert the string to an Uint16 array before encoding to base64. The problem with that approach is that it will double the payload size of the worker.

I think I am going to put the fix behind a flag since most source code does not have to support unicode characters, that way, of you need/want unicode support you can enable it.

**Comment by darionco** [comment]
Fixed in 0.7.0 with the addition of the `enableUnicodeSupport` option. See readme for more details.

**Comment by feichao93** [comment]
thanks a lot! 👍
